#!/usr/bin/python3
# -*- coding: UTF-8 -*-
# This file is auto-generated: DO NOT EDIT!

from edit_cfg import LinesB64, CrcKey

CONFIG_FILE = '/home/mks/klipper_config/printer.cfg'

# def:		upg
# upg:		Y
# grumat:	upg
												# BASE64 of the persistence area
RESET_CFG_PRO = LinesB64('QlpoOTFBWSZTWW+aJH4AAsX/gFAAEABI93/nP+3djr/v/3BAAm67gYOQSUyJoEmkfqeqPUB6hpvUm1AND1G2lGm1NsqCU9SE1PVJtQNoBNAGmI9AATQAAbVKAADQAaANNAAGgAACSU0mjSN6iek0xM1MBADAQMmAC0sLBCRrgJLUkFW/shw28ciDdz95IlGfDuIzn9evry0cmKBIRVhliBR//azjYwnDADFpIRKkIlEJEEkjZJHnRRDcdHS8Oh3OrZrOnIqng1PazX1tBk8QKaIFMBCfghPhAmAlgYkYUgTqNOwEe8FPd8tGYM+iSI12CJSDQy/FI06xSZommCIJoKoioIiiwbYeHxiCiqLAoqCkbk2LIrCKwiXYrIYQqkEoVSxx6lIyMlLuK3SxnmUpVZkaWygQc9KZ5LUTFrlits1L3xWcZZsJitrYuuowwqiqirCFlnKty8xmxQyrZlmlWFW+MnwTeUXapnqhZKuVBKcRC9mDGH7+7nXjvfHd7+zdu3V2YJCPsabZ40vodkhEtDMzGL7HSOPPDDR7tMfzysTSzjGmRvjlXtjGMY2wRCh/8+R8vT6M5duhIQykPmQKyAoRostpQkbUhGXAj4XL2SEZwKR6HgFOPFIRcv7dy83MX7e+YHVTqLjSBac6EiVtKEi0TGeryELBaJhYJEhDISGZohyc6vVrx0YCIsIkPAeh6CcUoyQ73iJtYmPIQSGgGHOU6MJrwSHpCJOZi1XW3pCKqHixrgchaXaJ3km9RXMIQc5GDwEWYZf8XckU4UJBvmiR+A==')
												# BASE64 of the persistence area
RESET_CFG_PLUS = LinesB64('QlpoOTFBWSZTWRWqGXgAAsl/gEAAEABI93/nP+3djr/v/3BAAm6mDKZBJTJJtJqeiTemoaBBtPUaIwAeSAmxBKepNTQaigAxAAAA0AABkOYBMBMjACMTEwmEwQ0xNMBEqIR6g9JoZDT1AADIaAAACkMJhASOKAktwES0fNzeGnU3wzwPonIxn+W+DB15M7qydF5RMFqy4DV6acpPeDSwA2VEsUSwBIghIzxRNwCuM1rwzO7c0eI5NXDRnoaHszWUtSZAUvApoKJaUSgFInDJFCQnGonEOLAcEkkIQZEDf8b9S3yuhQxwA1JiiY0OkWtPVfQEQWyVUFEYVEXqaLzDnqREbMSXguCCMQgYv1p3VrM4JdK3U1Tm06TRZzJN+6FjUzayvIiOeVolzqQ0tVsUYyqyXJk1zkLJMyYKRVBBVFdNU1z200gR1NDKnWb4ta2V76CqI32wZbXxNyS2JE8Y04JQTkmmiIX8tYt9O5zsv0X3dHndddRTakI8ceKe+T1OyQiapmZi9+d0jTxwtq5scfPZucklrmmomNEeTHxqrVW9gb1/Lch6u12eXL4b4ggmMi3KJsJDV8bpAkeSQjVYR2nLKnSEa4FBGd4BRfpSEVr3r/GSos8fqcDPLpymHIbIFRmBInxYUJGITGvLvEYBRt0Wywz1EgKSS2UtNOHVw1XaC4WJol7aLqVoVF7MLmvWJlaxbrLQKSghTS5dQZVYKVqImc1iy17FiQijA8WP1AxbBXVP+dswP+6ZBCDmNg2osw1f2LuSKcKEgK1Qy8A=')

# def:		upg
# upg:		Y
# grumat:	upg
X_MAX_PRO = '250'								# Plain value
X_MAX_PLUS = '310'								# Plain value
Y_DIR_PRO = 'PB6'								# Plain value
Y_DIR_PLUS = '!PB6'								# Plain value
Y_MIN_PRO = '0'									# Plain value
Y_MIN_PLUS = '-10'								# Plain value
Y_STOP_PRO = '0'								# Plain value
Y_STOP_PLUS = '-10'								# Plain value
Y_MAX_PRO = '250'								# Plain value
Y_MAX_PLUS = '310'								# Plain value
Z_MAX_PRO = '260'								# Plain value
Z_MAX_PLUS = '405'								# Plain value

# def:		grumat
# upg:		grumat
# grumat:	Y
HOME_OVR_PRO_CRC = CrcKey(0x1EAC1C68)			# CRC object of a value
												# BASE64 of a multiline value
HOME_OVR_PRO = LinesB64('QlpoOTFBWSZTWT56r1cABKMfgFLne3I/79x+v+feXlAEHgAAAABzAJpgEyGAAJgmAAAHMAmmATIYAAmCYAAAcwCaYBMhgACYJgAABzAJpgEyGAAJgmAAABUUiGimMmoyNTZQ0NGmmmmQxA8jKeDYbDtfxH7xYsWLFsYWMRYsM0QfMqQcTTTGMY3mcQdaugcSjMphPwFO5HAkns9i/rbcLgwwuGKxhW9JOw4nwN5oNpGacDnNjvIMEHTzzfU5TmN7IzK2uVUj51H25M9WeNWjM0mqNSKVmyykmypnZt2twg4Fe8xJB1nAxJBo2L57aq2qqrbaUpSqpSlKqqqrbbFi2lLFiqtqrbFiqtttt86QWJMlEcTvPIknWeM2lO0+B6Ifg5UpuXLLFMmGK9EkGH3lpaetJmjzHUet50aiME6k3DynIRqSODqPW6jQ8h0GD3PcNT2jRIP0ep7n6vUNH8DYk3LEG4SZP5HQ/cYGQ+I5mx3JBp27xrerkGg4PkwPkNaK2jRsHm8g2DMcr+UUlRSVFSPKen824qklUtKpaSSUknrKYKRYLFiyLVqhVSVKiirVttqVQp+nQOx8R8na9p4inoU4h2RBme1JMn0STm70g+L3joKd5Gp1vo1G1JO4qa3lffJ9VVaotpZJPmLJBwiHNVqSd55GeonQZskk3GbiawbUk4DYc7cJ6SSbXMTxHOZJJ4ydbWajY2m7kSTkSTQdx6RDCSajwPMMEg1pJrPEeDic55Yg6ZOpJhBrM0gzI8aSZJCZFCpBUg8RGjYTMzSDI7Eg5DkSTidJ/ZkZnSYO0pvcwqScCS+hypJuSTUdRkbDzRBR0jsKa3jPqMDWo8ESdNCD2VqGriYSDekG41GhSCmaQaNT27zlIyDQwcTBuIPefA7vBcz6H2KIqif+LuSKcKEgfPVerg==')
HOME_OVR_PLUS_CRC = CrcKey(0x649232BC)			# CRC object of a value
												# BASE64 of a multiline value
HOME_OVR_PLUS = LinesB64('QlpoOTFBWSZTWX/KBLsABKMfgFLne3I/79x+v+feXlAEHgAAAABzAJpgEyGAAJgmAAAHMAmmATIYAAmCYAAAcwCaYBMhgACYJgAABzAJpgEyGAAJgmAAABUUiAgGoyanhQwQ2mgEzUDNNJ+Go1H1fKPjFixYsWxhYxFiwzRB3lSDca9eMYxGUQdSuUbijcUwnoFPsjjJJ29q+y24XBhhcMVjCuJJOs3HzOI1jYRmnGchqeBBgg5uScVTgOE4mRmVscCpHfUfrkz0Z40a2ZrmiNCKVmyykmqpnZs2Nog4yvgYkg6jjMSQa2pem2qtqqq22lKUqqUpSqqqq22xYtpSxYqraq2xYqrbbbelILEmSiNx4HjSTqPEbCn1Pmec83ocKU3lyyxTJhivNJBh6C0tOxJmjsdJ0nU0EZk6E3zeHO0iuAjUkcjoOx0G05TmMHve8aHtGtIPW9T3vY9Q1vkNSTasQbRJk/keR8RgZD6Dhan2SDX9eIaXq3xrHG7mB3DSitg1tQ5/GNQzHA+aKSopKipHkP27G0qklUtKpaSSUknrKYKRYLFiyLVqhVSVKiirVttqVQp28o630Hc+r3G8U8qm4OuIMz3JJk+6ScPgkHc+I5SngRodT7tBsST7FTS8jzydFVaotpZJO8WSDjiHDVqSeB42egnKZskk2mbcaQbEk4xqORtE9JJNjhJvHIZJJ4idTSaDU2G3fSTfSTWO89IhhJNB+DnGCQaUk0m8fhuOQ8kQc0n5JMINJmkGZHiSTJITIoVIKkG8RraiZmaQZHWkG+b6SbjmP8MjM5jB9inE4RUk4yS+VwJJtSTQfkZGo54go5h1lNLxHQYGlR+ESc1CDtrQNG4wkHEkG00GspBTNINbQ9vEcBGQazBuMG0g+B9Dv/pcz7n6KIqif+LuSKcKEg/5QJdg')

# def:		upg
# upg:		Y
# grumat:	upg
MESH_MAX_PRO = '220,220'						# Plain value
MESH_MAX_PLUS = '290,290'						# Plain value

# def:		grumat
# upg:		grumat
# grumat:	Y
G29_PRO_CRC = CrcKey(0xF8CEE4BF)				# CRC object of a value
												# BASE64 of a multiline value
G29_PRO = LinesB64('QlpoOTFBWSZTWQw3laoAAHUfgEDkclA/5hx+rqWeADAAtmwlKAmNBMAIwAACRSnlMQaGhoBkADAVUkPUaHpDQ0DJo0ABFASBiYtFcDLmbhGMMYLwChO22223kQ0JKGpeTIlCE0k2BWrVFKE6xhX1CpSpfTeuNcES1Y4HEignQtIsqx6gj5kXRFEAfWB8TO0QuyDILBIfEODokE8E6F1HyhEYj8KidFaTQ0fxo3olcK4RfzxZ0SQ0dMBdyRThQkAw3lao')
G29_PLUS_CRC = CrcKey(0x7E1AC1F9)				# CRC object of a value
												# BASE64 of a multiline value
G29_PLUS = LinesB64('QlpoOTFBWSZTWQEQaJAAAHUfgEDkctA/5hx+rqWeADAA1iGNNBoAZNAZGmhiaMEiVPSYjIA0aAAA0BVJTT1CPCTamEPTTSbSME0kgKC+QJiyaoKq24lKJwXYFFLbbbbeFEkerW0pJlaJVJaWtc3si1oei9QZ0ljatWv4+nI2QmYL1xwJoaEYE1K92hPrUcpqVZ7UKkc+CGGJiXIs8w7PC1HlHhkpT2JMR8FTQixJoaPo0a0TXCuEft16tEyGjf/F3JFOFCQARBokAA==')

# def:		Y
WIPE_PRO_CRC_DEF = CrcKey(0x5119CB28)			# CRC object of a value
												# BASE64 of a multiline value
WIPE_PRO_DEF = LinesB64('QlpoOTFBWSZTWYc3XucAAnEfgEDmf3Irr8x+rqWeADABYMMEKiqeptTGjU8miYI09TINMEYRSoaAyABoAAAMgKlKE8kzRPUyDE0BpmiMQ0+AonAaQ0mIHheNIsKYswRoRYFwQPUEGoyqYnGvC0riDPyEX+CLnihhqGGpmZqqqqqtQLIu43kcBsHYMMON5ZNKpot0AUGINqLImzbty5kMyGeFdcNDShdJuCBijKaXwk0Fq8TtWqEyEqSFEeiwvl9KK0mM71ZWazxQaT3L0iH8hNh7FDAXHMk6uVGsu3FguMJUYC3aVGEykThsEnzaXGiJLOhJzfruiTpC0FS4WPYrAC/UW1ZBc4rALALQQCzAslKLSIP6B11ZgWQFgF3fxdyRThQkIc3XucA=')
WIPE_PLUS_CRC_DEF = CrcKey(0x53513B27)			# CRC object of a value
												# BASE64 of a multiline value
WIPE_PLUS_DEF = LinesB64('QlpoOTFBWSZTWd4Su94AAnEfgEDmf/Irr8x+rqWeADABYMbBEkpk0R6Q00NNAGgADQJKiZDTI0GTCGEZAYmAKlUT09U/UE00MmjTIGI9AmgZS4UTAohgIbzi1CiUpULy9FvBbEB6AgXFlSo1xUsitQLXiL7CLbPBgyQYMkYxjJJJJJJJJvgsRdpzGUhwjWI7Sw0NuMzKl85YASBUDSi6KBLtOqzaIWi5JkzgJqNgqQ0BsDWGNrROxkdRKCOgnowpoKqKLEuhiO9UqajwQaD3LsiH6hNh7FwsLTmSXvq41FvyYhaVKFhk+ChUxkTfUAlXvD2EiEnsgS/mBAhLJCWAy6arhJMAL+IubAF1isBYC/pAXEFu3Iu4Qf6D1WxBbgWAvb/i7kinChIbwld7wA==')
# upg:		Y
# grumat:	upg
WIPE_PRO_CRC_UPG = CrcKey(0xB77EDF4D)			# CRC object of a value
												# BASE64 of a multiline value
WIPE_PRO_UPG = LinesB64('QlpoOTFBWSZTWXcuviEAAWcfgEDmf/Irr8x+rqfeIDABezYEJU9RQekAZMgMQ0ZAaNACU9VRoAAAADQAAAFSiSeRNGTQGmgGgPUDQaepiiJcxmNVQoUmWlKMQWJKugqZlxRCcQSMSWpkCwTGJs4AORBE9BQSSFEVVVVVVVVWrACAXyUShEo3SFJMeMLakEA1MhGAgI4o3A5zQc95mSuNK0rRZZqcpvKoVZjM1KO9OcuVWNDOtdipasGcqlRlORjLjqOaSNRrNiwhtE8TWUNwvMF0kt2UdZf6G+LzIWmI0eZaYzOie3gknjoLzSG9hB9P1xoYB+K5V2yQog+wycDJBpkKQUg/FIM0G1dtDaJhROyzPBuQYKwKMZ/F3JFOFCQdy6+IQA==')
WIPE_PLUS_CRC_UPG = CrcKey(0x8B891807)			# CRC object of a value
												# BASE64 of a multiline value
WIPE_PLUS_UPG = LinesB64('QlpoOTFBWSZTWftfItsAAWofgEDmf/Irr8x+rqfeIDABebYASp6lP1QyNAxBoAGjJpoABqn+qoNGmjIYmIYmjJhAMmgKkkCmpk2nqCPU9CaMmh6hp6mNPVMmTjZREuai9ZRgVKqqXhcks6yxZeZFkXUZ1FVC14P0iYUVRS+AhAAAAAAAAA2wkhJLooUm1nY4CwkiSdCDrSyJIB6DEOBh4EsMrMDM8sUvt1OmqxstVqXXdTapSFNZtbDNm8EspypZmxdy9YUoe4+DEwO02SRtO83riHATxO8owNxoykmO+nzN35PeNxqMS8z/BicRrRP34pJ98zcbA5NIP89XShoHotxst8hSDzDVzNUGyQqCoPRUHLBwZcA4CaUnddrgwg0Wg8Nb/i7kinChIfa+RbY=')

# def:		N
# upg:		Y
# grumat:	upg
LINE_ONLY_PRO_CRC_UPG = CrcKey(0x9601896A)		# CRC object of a section
												# BASE64 of an entire section
LINE_ONLY_PRO_UPG = LinesB64('QlpoOTFBWSZTWYlHHbcAAq8fgEDnf/orr8x+r+ff8EACXGVAAcwAAAAAAAAAAJNVNTUepiAGBMgDQGmmmmgAcwAAAAAAAAAAFSSAjRPSmU2jU9TT1H6pmoGmaepGaMKZDBAopJM2xC5FlNCbla3WtalMZEwQyLlKSnsLTFUzWUpgf67/BPq9U5PliuxW5L55qcwc4fG7WnfaxVV9qHD87VcFRlpVC0kLKWyBLCBLarFEFQK4CqioqKqoqwGAqrhJIwIuLhfE9KpVFUkdjqUp7LmNifBTBgUuJXaKwOdqFSjBKUMsAKSSxjWeZIgruPGrWrQlRQzdon7MmxsPiP3I9aGpspqtepJcdMsrqLNrBmbS9tXFwltyFdL1HDTS1ubef2fyZAe4+B2Sd18E60R3H+FGJyPMZiY9/QbORvHzNhkXmHp+RkZl6JO3tCb3bwOR3ND3vu4wnB73iklD6rnI8VzZyMvmnQ6/F5TwuSqgbYTxWpT9MF2uFM9FmT1uLa9G6TwQU8lySTS5Zy3JxU/CE6N69fOwcAe2JFOlSSWSTnaTgZLwZvyST79c3sZYaZukX4sV7Vpg9EJnzXS3Br5IiqOjq2tmKSc90m6pI3NJ54NRkkm7+sW5rNWgrQb2L/xdyRThQkIlHHbc')
LINE_ONLY_PRO_CRC_GRU = CrcKey(0xC2007C15)		# CRC object of a section
												# BASE64 of an entire section
LINE_ONLY_PRO_GRU = LinesB64('QlpoOTFBWSZTWedMunwAArIfgEDnf/orr8x+r+ff8EACXGVAAcwAAAAAAAAAAJNVNTUepiAGBMgDQGmmmmgAcwAAAAAAAAAAFSSAjRPSmU2jU9TT1H6pmoGmaepGaMKZDBAopJM2xC4llNCbla32tal7GRLkMi5Skp7C0xVM1lKYH+u/wT6vVOT5YrsVuS+eanMHOHxu1p32sVVfahw/O1XBUZaVQtJCylsgSwgS2qxRBUCuAqoqKiqqKsBgKq4SSMCLi4XxPSqVRVJHY6lKey5jZPgoYMClCV2isDnahUowSlDLACkksY1nmSIUu48atatCVFDN2mSiP2Zti8+I/cj1oamymq16klx0yyuos2sGZtL21cXCW3IV0vUcNNLW5t5/Z/Jkge4+B2Sd18E60R3H+FGJyPMZiY9/QbORvHzNhkXmHp+RkZl6JO3tCb3bwOR3ND3vu4wnB73iklD6rnI8VzZyMvmnQ6/F5TwuSqgbYTxWpT9MF2uFM9FmT1uLa9G6TwQU8lySTS5Zy3JxU/CE6N69fOwcAe2JFOlSSWSTnaTgZLwZvyST79c3sZYaZukX4sV7Vpg9EJnzXS3Br5IiqOjq2tmKSc90m6pI3NJ54NRkkm7+sW5rNWgrQb2L/xdyRThQkOdMunw=')
LINE_ONLY_PLUS_CRC_UPG = CrcKey(0xA1FABFED)		# CRC object of a section
												# BASE64 of an entire section
LINE_ONLY_PLUS_UPG = LinesB64('QlpoOTFBWSZTWUvwCuEAAq8fgEDnf/orr8x+r+ff8EACXMVAAcwAAAAAAAAAAJNUKammgHqADIAANGgABzAAAAAAAAAAAVJIBT0U/SjTSeTU09R+qHohpmnpIybEmQwQKKSTNohciympNytrrWtSmMiYIZFylJT2FpiqZrKWYHzfXwT6NuZjyuK3FMxafwmmAXgGWuknxSgK/LAyN99DJWkLJDC4iBMJAmJViiCoFYCqioqKqoqwGAqrukkYETi4XxOhUqiqSOx1KU9lzGxPgpgwKXJcXYC4DjtSoqWYJapbJAC0koxwGUkSl3HjVrVqSooZu0T9WTRkaHxHtI6UNjmXLNlySxRovYmhezXFwltUK9LoNunqtbzbz+j+DID9z4HZJ3XwTrRHcf2UYnI+4zEx+vOacjeO80Mi8w6PkZGZeiTt7Qm928DkdzU977OMJwe94pJQ+i5yPFc05GXenO6/F5TwuSqgc0J4rUp+eC7bCmeqzJ0uLmefdJ4IKeS5JJrcs79ycVPTCc+9evnYOAP2iRT1KSSySehrOBkvBm/FJPt1zexlhrm9QvxYr2zXB54TPzXS3Bt5IiqOfq5mmKSei6TdUkbms++DYZJJu/nFubTZqK1G9i/8XckU4UJBL8ArhA==')
LINE_ONLY_PLUS_CRC_GRU = CrcKey(0x720F5A2F)		# CRC object of a section
												# BASE64 of an entire section
LINE_ONLY_PLUS_GRU = LinesB64('QlpoOTFBWSZTWQOkh/AAArIfgEDnf/orr8x+r+ff8EACXMVAAcwAAAAAAAAAAJNUKammgHqADIAANGgABzAAAAAAAAAAAVJECT0U/SjTSeU9TT1H6oeoGmnpkjJsSZjFAopJNG5C5LKak3q2wta1MGUiXQzLqUlPaWmSpospZifF8/FPk25mPK4rcUzFp/CaYBeAZa6SfFKAr8sDI330MlaQskMLiIEwkCYlWKIKgVgKqKioqqirAYCqu6SRgROTjhE6FSqKpI7HUpT23ZWT3qGLEpclxdgLgOO1KipZglqlskALSSjHAZSSil+XKrWrUlRQ0dpmoj8mjc0MT+x+pHShscy6zZdJYo3MGRuMGi5cS2qFet0G3T1Wt6OB/J+5mgfoe87JO7CCdaI7j+ijI7z6jQTL585u7zgPA3GZgY9HwMzQwRJ29oTg7eJ3nc1Pc+jlCcXueSSUPku7zyXbu8z8E53X5POeN0qoHNCeS1KfhivtjTTVZm6XJzPTvk8UFPNdJJrdZ4b05KeuE5+DBhOwcQfnEinsUklkk9TWcTNgDR9ySfTrnBlLDXR7BhkyYNmuL0wmnovLcW3miKo5+rmbskk9V5N9SRvaz64thmkm/+Mm9tNmorUcGT/xdyRThQkAOkh/AA==')

# def:		Y
# upg:		Y
# grumat:	upg
LINE_PRO_CRC_DEF = CrcKey(0xC0A17064)			# CRC object of a value
												# BASE64 of a multiline value
LINE_PRO_DEF = LinesB64('QlpoOTFBWSZTWSKwPnMAARqfgEDnfvgLhgh+r+ff0DABmZMpCSo9Cap/qTFNNMmEGT1ADQ3pAkSmoAAAGgAAAAVRE1E9JiDINAYmhoGmhphsiH6orJVC9iRU4zIuuTctEKCgsKLmzM3xubKm1bcrgUey44Jj7k35VO6kRRw7okTCRF9tttttpptvCIaRoK8sA0XhkDAyAyhApydMcylJQ4jKkQBwAowTMpmU6F5qcSUMDUXnmURzakYWl6C6prGBpGJjMRKGNHSvIRnQaEJ3bbWCX1sBG2BDxMEjqPAoIqMRjEoX4ljn9n5GQcmGr+Rkh0iRXEkNfGom5WWGgcvsdcQVCCQ+lrRWPhryQzxDnockQzQMLqVQqhUyojJH6I05BoHIkk8zSNMkZi2BgkTru4eTKHYXndQQVNTMWyEZ2EXKY4c4qQh8olpgFxa4KWdaz/F3JFOFCQIrA+cw')
LINE_PLUS_CRC_DEF = CrcKey(0x35BF6E45)			# CRC object of a value
												# BASE64 of a multiline value
LINE_PLUS_DEF = LinesB64('QlpoOTFBWSZTWb5Q60QAARyfgEDnengLhgh+r+ff0DABmZMoElTanpNU/1JtSaYmQaHqANBskGakkAAHqAAAAACpQiaBNGTRoBo0ANNAwvSPxVahZGRlSxmM665S5fIqKi8VXN2lwm9usei/etiVeq4/lI+qOGhXqrJUgvptSTajCAAADGAYk0NrQrNE0NYEQAksqQqUJzU2Ik5KggiMjahJcElnhSlFKUpTBkKDaxqIxNp4mUqmnamDaymBfcZhoMbyGZjRnTWyETUhsRTf7u4JfO4Eb7S3vKpHQdxkIsMRjEyK4l0H7q5GYcmayXwSSISJknJjVewpBIuNZBW6F9gvxdEfK++Wnu3cUa5GqpxyOWDBsWRZFgqOMkfgjbmGsgcmoobRqEzQX2mlIpLDwxZW9RU3ZCCxstBfMRqYRgqEBzdTERm5eaQwLzmSc3jn+LuSKcKEhfKHWiA=')
LINE_PRO_CRC_UPG = CrcKey(0x92CA8881)			# CRC object of a value
												# BASE64 of a multiline value
LINE_PRO_UPG = LinesB64('QlpoOTFBWSZTWQn5fbcAABwfgEDkQBAJBggOrqXesCAAlUJSmgA2oAAeUCU1NEepNNAGJk08pNmK+oSlMZxouSSgTQ0yjGpxr3p5gMKkw7JU4x2ekwwqOjEEcUo5CUgCnww6X1kTUZECJFhF5wXDnQw5t4rYe8oOSLOcih1Mj8XckU4UJAJ+X23A')
LINE_PLUS_CRC_UPG = CrcKey(0x92CA8881)			# CRC object of a value
												# BASE64 of a multiline value
LINE_PLUS_UPG = LinesB64('QlpoOTFBWSZTWQn5fbcAABwfgEDkQBAJBggOrqXesCAAlUJSmgA2oAAeUCU1NEepNNAGJk08pNmK+oSlMZxouSSgTQ0yjGpxr3p5gMKkw7JU4x2ekwwqOjEEcUo5CUgCnww6X1kTUZECJFhF5wXDnQw5t4rYe8oOSLOcih1Mj8XckU4UJAJ+X23A')

# def:		upg
# upg:		Y
# grumat:	upg
POINT0_PRO_CRC = CrcKey(0x15979530)				# CRC object of a value
												# BASE64 of a multiline value
POINT0_PRO = LinesB64('QlpoOTFBWSZTWSig+0YAAH8fgEDkdzAJhgh+LqWeADAAoBEpR6p+qfqjNBG1DTTR6YoYwmJoMEYhkYTDGExNBgjEMjCZcqqUPIKAWNpA2LujIFQDsAUtJJJGMl1gGNibXCJIHqBMDBJSUwOQ2ORcxMToNgqFjgcUTQDJZ/QetagdvcXp6AW1XIzNwGoGZS5b9QgvgC/mvFCLFzIuS10A0A1g67N61WL9f4u5IpwoSBRQfaMA')
POINT0_PLUS_CRC = CrcKey(0x1F05E6CB)			# CRC object of a value
												# BASE64 of a multiline value
POINT0_PLUS = LinesB64('QlpoOTFBWSZTWaIII2EAAH8fgEDkfzAJhgh+LqWeADAAoBEpSfpoQmTQ9EGg9TxQwaaNNMJiZMBA0wwaaNNMJiZMBA0zEqqULgoBYxIG5eMZAqAdwCl8kkkYyYrAOtieDyiSBwAnI3pKSnidBsdDAyOpcZD6FwXnM8kTUDNZ+wfitQO/qLliBbZczQ4AbAaFMC34hBf4DC9eaEWLoRc1rqBqBtB23cVqsX2/xdyRThQkKIII2EA=')

# def:		upg
# upg:		Y
# grumat:	upg
POINT1_PRO_CRC = CrcKey(0xB4193AA8)				# CRC object of a value
												# BASE64 of a multiline value
POINT1_PRO = LinesB64('QlpoOTFBWSZTWXroEPUAAIAfgEDkdzAJhgh+LqWeADAApkIlKPU00aaAAAGgxhMTQYIxDIwmBUpQ000BoNAA00LSqpQyBQCwoQIt0ZAxgHYApZJJJGMlqwDhYTOVb4kgXAS8vSUlKmsbG1jWLnFcmRUVti2I+i+Snuidaqh34JLs4r/SXsGkfhgxWK/UKJPgszSWwpGL9Ivta4AYAfoP7FoWqxef8XckU4UJB66BD1A=')
POINT1_PLUS_CRC = CrcKey(0xE5388F82)			# CRC object of a value
												# BASE64 of a multiline value
POINT1_PLUS = LinesB64('QlpoOTFBWSZTWYS9t2YAAIAfgEDkf7AJhgh+LqWeADAApkIlJNNGgAAABkMMjTTTIwmRgmgMBUqQ009QADQANAtK1ShhCgFhaQKlzxkCsA7gFMUkkkYyWrAONhMDpiSBlAmgyJKSmc2DYbFFrg2rU3MJRRqa4j6LpKvVSdK6x23pLcgs/SXPjKPw+L1FnmFST2KYpNMKoxfxF+LXcBcBfBvqzLWsXn/F3JFOFCQhL23ZgA==')

# def:		upg
# upg:		Y
# grumat:	upg
POINT2_PRO_CRC = CrcKey(0x8AF75754)				# CRC object of a value
												# BASE64 of a multiline value
POINT2_PRO = LinesB64('QlpoOTFBWSZTWfbLx3oAAH8fgEDkdzAJhgh+LqWeADAAoBEqJ6p+p6k9T1MhtQNMaYoYwmJoMEYhkYTDGExNBgjEMjCZuVKDAPIsQL1wjIFADoAXVkkkjGSywDgZbyUcYkgYATExSXS6pyGpyLyxkZHMdxQKnqcUTUDNZ3g/lKAdPgXnwArsuZoYAbAaF1ivZCC+ALb14oRYuhFzWmoGoG0Ha/0Wixfv/F3JFOFCQ9svHeg=')
POINT2_PLUS_CRC = CrcKey(0x78B708C4)			# CRC object of a value
												# BASE64 of a multiline value
POINT2_PLUS = LinesB64('QlpoOTFBWSZTWRN68xwAAIAfgEDkdzAJhgh+LqWeADAApkIlJNNNGmjQAAGgxhMTQYIxDIwmBUqQyZAaDIANNC0rVKGUKAWFpAqW6MgVgHYApmkkkjGTOsA4WEyN8SQLgJeaElJS8wGwwXtC9UuSxUUq21bEfRhJR7oTrTSO/FJdpGf9Jgxah+GLJYz+oUJPgsrkthRGL9Ivta8QMQP0H9VpWtYvT+LuSKcKEgJvXmOA')

# def:		upg
# upg:		Y
# grumat:	upg
POINT3_PRO_CRC = CrcKey(0x7482C28D)				# CRC object of a value
												# BASE64 of a multiline value
POINT3_PRO = LinesB64('QlpoOTFBWSZTWfBG+lIAAIEfgEDkdTAJhgh+LqWeADAApkIlKPSaNNAAADIYZGBNMCZDE0YBUpQ000BoZABpoVKqlCgUAsKECLdGQMoB3AKWSSSRjJasAznG0lCrfEkC4CXl6SkpU2ErWspYvXrkqK25bEfRhJT3ROtVQ73JL9Ir/SYMWsfhiyWK/UKJPgs0SWwosX8Rfi1wAwAxg45L1qsXp/F3JFOFCQ8Eb6Ug')
POINT3_PLUS_CRC = CrcKey(0x774DCC99)			# CRC object of a value
												# BASE64 of a multiline value
POINT3_PLUS = LinesB64('QlpoOTFBWSZTWenl510AAIEfgEDkd7AJhgh+LqWeADAAo0IlJPU0ymE2ibRNMJjQYNNGmmExMmAgaYJKgAaAAAAFxVUoZwoBaXECxdUZAqAdACmiSSSMZL1gGNpMzsiSBpAms+klJTWYDaYGJeYm44DeZwqXFx9m1EyA8LP+DzrUDp+CVzAIPkujwYB8B4NxEHCBoS7AihSoQRYvoi+FrkBkB7g+7NS1WLz+C7kinChIdPLzroA=')

# def:		upg
# upg:		Y
# grumat:	upg
POINT4_PLUS_CRC = CrcKey(0xE6CB868E)			# CRC object of a value
												# BASE64 of an entire section
POINT4_SEC_PLUS = LinesB64('QlpoOTFBWSZTWc61NhAAAJKfgEDkdzALhgh+rqffIDAA+21QkpqmnlPU08poeoZAAeoAaeqoaZGJhMjACMBAVJSnhTIDEPUABmk0/VNTCRLmJdIyalG9gyeeUnXUqpdV6HwhOBzQAAAwwQMwyQqeyOjRjIEvCZEZJDmc1xQUChEvMB5eLgSIBExlxoS3uSXsW0F2+kvY0M8w3M8WLyU0dkL/6TQ8D4BMR9QehnH4rnKGaqREZJWoJYFCrweESpKks53IsvHKTNrVg6bQsNdJ3t1jJPelkLbEusyf8XckU4UJDOtTYQA=')

# def:		upg
# upg:		Y
# grumat:	upg
POINT5_PLUS_CRC = CrcKey(0xE93142D3)			# CRC object of a value
												# BASE64 of an entire section
POINT5_SEC_PLUS = LinesB64('QlpoOTFBWSZTWXZffsMAAJOfgEDkd7ALhgh+rqffIDAA+21Qkkpp5TE8oG1DQ0APUANPVUNMjEyaZGATCYTQFSUp4UyDTQGjQDE9TJ+qaGEiXMS6Rk0KODBk25SaqlVLqvQ+UJwOKAAAGGCBmGSFT0RybuMgS7JkRkUM5nZyYoEysvNxMvFEwIBYWDGg0pcGSnEWzF3CkvY0NmwPV54sW1TNqhf/SZh4HwCQj6g9DmPxTMXGWiRWOSVqCO0uKPHjEqSpLOdyLLxyk8mlWDptCw00ngaqnJPelkLakukiX8XckU4UJB2X37DA')

# def:		upg
# upg:		Y
# grumat:	upg
POINT6_PLUS_CRC = CrcKey(0x8CED7802)			# CRC object of a value
												# BASE64 of an entire section
POINT6_SEC_PLUS = LinesB64('QlpoOTFBWSZTWULGFZEAAJOfgEDkdzALhgh+rqffIDAA+21Qkpqmn6k0yeoH6oaAAeoAaeqoaZGJhMjACMBAVJSnhJoDQHqaAYajT9U52EiXMS6Rk1KODBk25SddSql1XofKE4HNAAADDBAzDJCp7I6NGMgS8JkRmZEmk0yBVkF5tILi8WMYcJHAsM5oS3ySn6LaC7hSXsaGeYdTPFi2qaO2F/9JoHgesJiPqD0NI/FMpBdRIsGSVqDJsIKOPKJUlSWanIsvHKTza1YOm0LDXSeJpqZJ3SxFtSXSZP+LuSKcKEghYwrIgA==')

# def:		upg
# upg:		Y
# grumat:	upg
HOLD_CURRENT_Z_LOW = '0.8'						# Plain value
HOLD_CURRENT_Z_HI = '0.9'						# Plain value

# def:		upg
# upg:		Y
# grumat:	upg
EXTRUDER_ACCEL_LOW = '6000'						# Plain value
EXTRUDER_ACCEL_MID = '7000'						# Plain value
EXTRUDER_ACCEL_HI = '8000'						# Plain value

# def:		upg
# upg:		Y
# grumat:	upg
EXTRUDER_CURRENT_LOW = '0.8'					# Plain value
EXTRUDER_CURRENT_MID = '0.9'					# Plain value
EXTRUDER_CURRENT_HI = '1.0'						# Plain value

# def:		upg
# upg:		Y
# grumat:	upg
PROBE_X_OFFSET = '-17'							# Plain value
PROBE_Y_OFFSET = '17'							# Plain value
PROBE_SPEED = '10.0'							# Plain value
PROBE_SAMPLE = '2'								# Plain value
PROBE_RESULT = 'average'						# Plain value
PROBE_TOLERANCE = '0.03'						# Plain value
PROBE_RETRIES = '3'								# Plain value

# def:		grumat
# upg:		grumat
# grumat:	Y
PROBE180_X_OFFSET = '-18'						# Plain value
PROBE180_Y_OFFSET = '14'						# Plain value
PROBE180_SPEED = '3.0'							# Plain value
PROBE180_LIFT = '12.0'							# Plain value
PROBE180_SAMPLE = '4'							# Plain value
PROBE180_RESULT = 'median'						# Plain value
PROBE180_TOLERANCE = '0.028'					# Plain value
PROBE180_RETRIES = '5'							# Plain value

# def:		N
# upg:		N
# grumat:	Y
SCREWS_PRO_CRC = CrcKey(0xDD0B2564)				# CRC object of a section
												# BASE64 of an entire section
SCREWS_PRO = LinesB64('QlpoOTFBWSZTWQ4BrzQAAJ+fgEDmfbALBgmKr/feoDABEwDGmg0AMmgMjTQxNGCU9VJ+pAGmgAAAAAqigQg9Jp6npqZMhkGm0ykkRFRAhAh79LQFFCyUmvFStatczYWVZshBwiC0kDUKqqqqqqAkGAg3rYh590ymZ0jIkkuJNyS8qLxYsWqXy1ixxlDPrVBuVIb2Ho2r5eC1a1tjJ4uT3Q5QbBUVkJ5lMQpQxGcHwj77FBDaajEudSsodIhPFoLUNCYHTK4VRCgnUa7Ds0mJCTsYOKDmuQvYFmpKU4K3kd+dMGb1Ibf8XckU4UJAOAa80A==')
SCREWS_PLUS_CRC = CrcKey(0xBF4D99A2)			# CRC object of a section
												# BASE64 of an entire section
SCREWS_PLUS = LinesB64('QlpoOTFBWSZTWfi9wBwAAQCfgEDmf7ALBgmKr/feoDABYYGEp6pNEAaAAAAADAA0aGjCMmg0aaAwKkpT9QmajTBMgBkaGmEmEQViCRCACQe/QpIJSFJlJrwzaVVVWudE2aqqrOoAOEAWEAbwqqqqqqqqqqtYpBIAvAGsvwBbLIR9DLcUVFaCCgDUSIxkUBE5DUK5Vyrl5YpLnU1O9hYGttZ0mR7UHT+tJPJYPN463g2Uys7QzNDO0NLmzNz3DdJNSSxpTCC75LQdQcUnSSfCb+Sfia0sC8vTiln8mBLnCCtrEncGJUScOepJaC4vS7IZsVqpVVTkxmUFJyNj4STe0h3thhxypUpsYFkzl/S0k6MoCuF3JFOFCQ+L3AHA')
SCREWS180_PRO_CRC = CrcKey(0x5D997DD1)			# CRC object of a section
												# BASE64 of an entire section
SCREWS180_PRO = LinesB64('QlpoOTFBWSZTWQ3z6PMAAJ+fgEDmfzALBgmKr/feoDABEwDGmg0AMmgMjTQxNGCU9UTUANAAAAAAqihNCM0nqep6amTIZBpjKVEEYAQSEIEPfpZBKS1FDXXRVWuc5qqzoEHCILCQN8VVVVVVUBIakN7XELfOZTM6DEkSXEm5JQvSlUXlapYpfLYK3GUMutUG5UhvYejavlqWLGxaxa3J7ocoLRUZiE8ymIUodhlB8I++5QQ2mk7FzqZih0iE8WcsQzpgdMbhVEKCdJsrO7QdiEncwcUHNchewK9KUpwZnkeOVMGT1Ibf8XckU4UJAN8+jzA=')
SCREWS180_PLUS_CRC = CrcKey(0xF1B6B503)			# CRC object of a section
												# BASE64 of an entire section
SCREWS180_PLUS = LinesB64('QlpoOTFBWSZTWYHNesIAAQCfgEDmf/ALBgmKr/feoDABekAGqf+qqj0AnpoAQwEwJgGBkGQAGI0GQyAwKklPSmptqT0wjaiYjJowYJcRqUKSUCkcN6qWLWVS7B49d6wACun5pUgBTZkkm6iSWkkiqAAAAAFcJRPiSSqSTTL9A2vwORuxqlVSqrMkzDwWSxpxVkpZVldqXFKLosztzBoYMn9bEmL+UHPfeSeC4eL9ZO93U0tbY1NjW2Nrk1PV5h6yTsSXNqdALf4vBmDgk5yT0T24p8JuS4MTFOCXb0wSz6gr0Z06wzqiT65diS8FjFLaDVnvVKqqcXSaQUnEyeaSf9tDtZHR0ypUpkwXTWY87yTm0g3fYu5IpwoSEDmvWEA=')

# def:		N
# upg:		N
# grumat:	Y
												# BASE64 of an entire section
HOST_TEMP = LinesB64('QlpoOTFBWSZTWSr3Ae8AAEQfgEjkeFALDBkKq2/e4DAA0qgqlEaDIYgGhoAepoJFJP0kYmQ00AADQMNDJkDIxBiZNDTEAqwaPHCQevRTMo55swNaOFp7blKALBTGFEhjbbbuYMJZB3C0FBqNl94VEcWG+397mqEWWJLfTIZWC5ed4nhJ9/e2eVKOpvVxSfMEEBZNEVxjYUzKT4KdlOKWBNlVyDGWAFCOV0sdZoiek5poa02pUVQ2wqT4YG5ao4GZWSgMh0GV60bYGVLYiqCS/i7kinChIFXuA94=')
												# BASE64 of an entire section
MCU_TEMP = LinesB64('QlpoOTFBWSZTWbAITgQAAE+fgEjkfBALBg0Kq2fe4DAA20DGTTIGTQyDI0wIwaak0AGmgAAABFIqfk1Jmmo9T1B6jag08k9SgvEIHOEkdT9rMl0tYIb87zYiCUqCclqFA4oEEkkkmYoCgUsGZEYGrC22V9ASiQP4skm2+1Q0oaQGWRyMrjMg4G5gdx4J9BJOxdAGtl+E4nALgwxUoNqpT+pSh1WeqHieWsQwVmWwU1l2Qmtdp8hx4DmQNhsmKRvunM5hf5rMZGhBvinpQmBYMkvqSf8XckU4UJCwCE4E')
